--- ./vanilla//drivers/char/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/char/Makefile	2012-05-23 10:43:57.463935515 +0300
@@ -7,6 +7,11 @@
 #
 FONTMAPFILE = cp437.uni
 
+ifeq ($(CONFIG_ARM),y)
+# This warning will never go away until a keyboard is defined for this target.
+CFLAGS_REMOVE_keyboard.o = -Werror
+endif
+
 obj-y	 += mem.o random.o tty_io.o n_tty.o tty_ioctl.o tty_ldisc.o tty_buffer.o tty_port.o
 
 obj-$(CONFIG_LEGACY_PTYS)	+= pty.o
@@ -70,6 +75,8 @@
 
 obj-$(CONFIG_APM_EMULATION)	+= apm-emulation.o
 
+obj-$(CONFIG_DIAG_CHAR)         += diag/
+
 obj-$(CONFIG_DTLK)		+= dtlk.o
 obj-$(CONFIG_R3964)		+= n_r3964.o
 obj-$(CONFIG_APPLICOM)		+= applicom.o
@@ -107,11 +114,14 @@
 obj-$(CONFIG_HANGCHECK_TIMER)	+= hangcheck-timer.o
 obj-$(CONFIG_TCG_TPM)		+= tpm/
 
+obj-$(CONFIG_DCC_TTY)		+= dcc_tty.o
 obj-$(CONFIG_PS3_FLASH)		+= ps3flash.o
 
 obj-$(CONFIG_JS_RTC)		+= js-rtc.o
 js-rtc-y = rtc.o
 
+obj-$(CONFIG_MSM_ROTATOR)	+= msm_rotator.o
+
 # Files generated that shall be removed upon make clean
 clean-files := consolemap_deftbl.c defkeymap.c
 
