--- ./vanilla//drivers/input/keyboard/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/input/keyboard/Makefile	2012-05-23 10:43:57.791935502 +0300
@@ -36,4 +36,9 @@
 obj-$(CONFIG_KEYBOARD_TOSA)		+= tosakbd.o
 obj-$(CONFIG_KEYBOARD_TWL4030)		+= twl4030_keypad.o
 obj-$(CONFIG_KEYBOARD_XTKBD)		+= xtkbd.o
+obj-$(CONFIG_KEYBOARD_QCIKBD)       += qci_kbd.o
 obj-$(CONFIG_KEYBOARD_W90P910)		+= w90p910_keypad.o
+obj-$(CONFIG_KEYBOARD_I2C_MSM)		+= msm-i2ckbd.o
+obj-$(CONFIG_KEYBOARD_PMIC8058)		+= pmic8058-keypad.o
+obj-$(CONFIG_RMT_CTRL_NEC)		+= rmt_ctrl.o
+obj-$(CONFIG_REMOTE_CONTROL_GPIO)	+= rmt_ctrl_gpio.o
