--- ./vanilla//drivers/net/wireless/libra/Makefile	1970-01-01 03:00:00.000000000 +0300
+++ ./default//drivers/net/wireless/libra/Makefile	2012-05-23 10:43:58.579935466 +0300
@@ -0,0 +1,6 @@
+
+# Makefile for wlan sdio if driver
+
+librasdioif-objs += libra_sdioif.o
+
+obj-$(CONFIG_LIBRA_SDIOIF) += librasdioif.o
