--- ./vanilla//include/linux/Kbuild	2010-02-23 17:38:51.000000000 +0200
+++ ./default//include/linux/Kbuild	2012-05-23 10:44:04.537935201 +0300
@@ -384,3 +384,12 @@
 objhdr-y += version.h
 header-y += wimax.h
 header-y += wimax/
+
+header-y += msm_mdp.h
+header-y += msm_kgsl.h
+header-y += msm_q6venc.h
+header-y += msm_q6vdec.h
+header-y += msm_audio.h
+header-y += msm_audio_aac.h
+header-y += android_pmem.h
+
