--- ./vanilla//drivers/input/accelerometer/Makefile	1970-01-01 03:00:00.000000000 +0300
+++ ./default//drivers/input/accelerometer/Makefile	2012-05-23 10:43:57.782935502 +0300
@@ -0,0 +1,12 @@
+#
+# Makefile for the accelerometer drivers.
+#
+
+# Each configuration option enables a list of files.
+
+
+
+obj-$(CONFIG_ACCELEROMETER_ADXL345)	+= adxl345.o
+obj-$(CONFIG_ACCELEROMETER_ST_L1S35DE)	+= gs_st.o
+obj-$(CONFIG_ACCELEROMETER_MMA7455L)	+= gs_freescale.o
+
