--- ./vanilla//drivers/gpu/msm/Makefile	1970-01-01 03:00:00.000000000 +0300
+++ ./default//drivers/gpu/msm/Makefile	2012-05-23 10:43:57.687935505 +0300
@@ -0,0 +1,21 @@
+ccflags-y := -Iinclude/drm
+
+msm_kgsl-y = \
+	kgsl_drawctxt.o \
+	kgsl_cmdstream.o \
+	kgsl.o \
+	kgsl_log.o \
+	kgsl_mmu.o \
+	kgsl_ringbuffer.o \
+	kgsl_sharedmem.o \
+	kgsl_yamato.o \
+	kgsl_g12_drawctxt.o \
+	kgsl_g12_cmdwindow.o \
+	kgsl_g12_cmdstream.o \
+	kgsl_g12.o
+
+msm_kgsl-$(CONFIG_MSM_KGSL_DRM) += kgsl_drm.o
+
+msm_kgsl-objs = $(msm_kgsl-y)
+
+obj-$(CONFIG_MSM_KGSL) += msm_kgsl.o
