--- ./vanilla//drivers/regulator/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/regulator/Makefile	2012-05-23 10:43:58.744935459 +0300
@@ -25,5 +25,7 @@
 
 obj-$(CONFIG_REGULATOR_TPS65023) += tps65023-regulator.o
 obj-$(CONFIG_REGULATOR_TPS6507X) += tps6507x-regulator.o
+obj-$(CONFIG_REGULATOR_PMIC8058) += pmic8058-regulator.o
+obj-$(CONFIG_REGULATOR_PMIC8901) += pmic8901-regulator.o
 
 ccflags-$(CONFIG_REGULATOR_DEBUG) += -DDEBUG
