--- ./vanilla//arch/arm/mach-msm/qdsp6v2/Makefile	1970-01-01 03:00:00.000000000 +0300
+++ ./default//arch/arm/mach-msm/qdsp6v2/Makefile	2012-05-23 10:43:53.984935670 +0300
@@ -0,0 +1,4 @@
+obj-y += audio_dev_ctl.o snddev_data.o
+obj-$(CONFIG_MARIMBA_CODEC) += snddev_icodec.o
+obj-y += snddev_ecodec.o
+
