--- ./vanilla//arch/arm/mm/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//arch/arm/mm/Makefile	2012-05-23 10:43:54.071935667 +0300
@@ -88,3 +88,5 @@
 obj-$(CONFIG_CACHE_L2X0)	+= cache-l2x0.o
 obj-$(CONFIG_CACHE_XSC3L2)	+= cache-xsc3l2.o
 
+obj-$(CONFIG_VCM)		+= vcm.o vcm_alloc.o
+obj-$(CONFIG_VCM_MM)		+= vcm_mm.o
