--- ./vanilla//drivers/usb/gadget/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/usb/gadget/Makefile	2012-05-23 10:43:59.575935422 +0300
@@ -28,10 +28,30 @@
 obj-$(CONFIG_USB_CI13XXX)	+= ci13xxx_udc.o
 obj-$(CONFIG_USB_S3C_HSOTG)	+= s3c-hsotg.o
 obj-$(CONFIG_USB_LANGWELL)	+= langwell_udc.o
+obj-$(CONFIG_USB_MSM_72K)	+= msm72k_udc.o
 
 #
 # USB gadget drivers
 #
+ifeq ($(CONFIG_USB_ANDROID_DIAG),y)
+F_DIAG = f_diag.o
+endif
+
+ifeq ($(CONFIG_USB_ANDROID_CDC_ECM),y)
+F_ECM = f_ecm.o
+endif
+ifeq ($(CONFIG_USB_F_SERIAL),y)
+F_SERIAL = f_serial.o
+endif
+
+ifeq ($(CONFIG_USB_ANDROID_RMNET),y)
+F_RMNET = f_rmnet.o
+endif
+
+ifeq ($(CONFIG_USB_ANDROID_RNDIS),y)
+F_RNDIS = rndis.o f_rndis.o
+endif
+
 g_zero-objs			:= zero.o
 g_audio-objs			:= audio.o
 g_ether-objs			:= ether.o
@@ -41,6 +61,10 @@
 g_file_storage-objs		:= file_storage.o
 g_printer-objs			:= printer.o
 g_cdc-objs			:= cdc2.o
+g_android-objs			:= android.o f_adb.o f_mass_storage.o \
+					u_serial.o f_acm.o u_ether.o \
+					$(F_ECM) $(F_SERIAL) $(F_DIAG) \
+					$(F_RMNET) $(F_RNDIS)
 
 obj-$(CONFIG_USB_ZERO)		+= g_zero.o
 obj-$(CONFIG_USB_AUDIO)		+= g_audio.o
@@ -51,4 +75,5 @@
 obj-$(CONFIG_USB_G_PRINTER)	+= g_printer.o
 obj-$(CONFIG_USB_MIDI_GADGET)	+= g_midi.o
 obj-$(CONFIG_USB_CDC_COMPOSITE) += g_cdc.o
+obj-$(CONFIG_USB_ANDROID)	+= g_android.o
 
