--- ./vanilla//drivers/hwmon/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/hwmon/Makefile	2012-05-23 10:43:57.697935506 +0300
@@ -73,6 +73,7 @@
 obj-$(CONFIG_SENSORS_MAX1111)	+= max1111.o
 obj-$(CONFIG_SENSORS_MAX1619)	+= max1619.o
 obj-$(CONFIG_SENSORS_MAX6650)	+= max6650.o
+obj-$(CONFIG_SENSORS_MSM_ADC)	+= msm_adc.o
 obj-$(CONFIG_SENSORS_PC87360)	+= pc87360.o
 obj-$(CONFIG_SENSORS_PC87427)	+= pc87427.o
 obj-$(CONFIG_SENSORS_PCF8591)	+= pcf8591.o
