--- ./vanilla//drivers/gpu/drm/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/gpu/drm/Makefile	2012-05-23 10:43:57.649935508 +0300
@@ -4,12 +4,14 @@
 
 ccflags-y := -Iinclude/drm
 
+CFLAGS_REMOVE_drm_edid.o += -Werror
+
 drm-y       :=	drm_auth.o drm_bufs.o drm_cache.o \
 		drm_context.o drm_dma.o drm_drawable.o \
 		drm_drv.o drm_fops.o drm_gem.o drm_ioctl.o drm_irq.o \
 		drm_lock.o drm_memory.o drm_proc.o drm_stub.o drm_vm.o \
 		drm_agpsupport.o drm_scatter.o ati_pcigart.o drm_pci.o \
-		drm_sysfs.o drm_hashtab.o drm_sman.o drm_mm.o \
+		drm_platform.o drm_sysfs.o drm_hashtab.o drm_sman.o drm_mm.o \
 		drm_crtc.o drm_modes.o drm_edid.o \
 		drm_info.o drm_debugfs.o drm_encoder_slave.o
 
