--- ./vanilla//drivers/spi/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/spi/Makefile	2012-05-23 10:43:59.200935439 +0300
@@ -33,6 +33,8 @@
 obj-$(CONFIG_SPI_XILINX)		+= xilinx_spi.o
 obj-$(CONFIG_SPI_SH_SCI)		+= spi_sh_sci.o
 obj-$(CONFIG_SPI_STMP3XXX)		+= spi_stmp.o
+obj-$(CONFIG_SPI_QSD)			+= spi_qsd.o
+obj-$(CONFIG_SPI_QUP)			+= spi_qsd.o
 # 	... add above this line ...
 
 # SPI protocol drivers (device/link on bus)
