--- ./vanilla//drivers/net/wireless/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/net/wireless/Makefile	2012-05-23 10:43:58.498935470 +0300
@@ -62,3 +62,6 @@
 obj-$(CONFIG_WL12XX)	+= wl12xx/
 
 obj-$(CONFIG_IWM)	+= iwmc3200wifi/
+
+obj-$(CONFIG_BCM4329)	+= bcm4329/
+obj-$(CONFIG_LIBRA_SDIOIF)	+= libra/
