--- ./vanilla//drivers/i2c/chips/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/i2c/chips/Makefile	2012-05-23 10:43:57.723935504 +0300
@@ -10,10 +10,16 @@
 # * I/O expander drivers go to drivers/gpio
 #
 
+obj-$(CONFIG_SENSORS_AKM8973)	+= akm8973.o
+obj-$(CONFIG_SENSORS_AKM8976)	+= akm8976.o
 obj-$(CONFIG_DS1682)		+= ds1682.o
+obj-$(CONFIG_SENSORS_PCA963X)	+= pca963x.o
 obj-$(CONFIG_SENSORS_TSL2550)	+= tsl2550.o
+obj-$(CONFIG_SENSORS_MT9T013)	+= mt9t013.o
+obj-$(CONFIG_VP_A1026)		+= a1026.o
 
 ifeq ($(CONFIG_I2C_DEBUG_CHIP),y)
 EXTRA_CFLAGS += -DDEBUG
 endif
 
+obj-$(CONFIG_SENSORS_LIS3XX)		+= lis3xx.o
