--- ./vanilla//drivers/media/radio/Makefile	2010-02-23 17:38:51.000000000 +0200
+++ ./default//drivers/media/radio/Makefile	2012-05-23 10:43:57.941935495 +0300
@@ -22,5 +22,5 @@
 obj-$(CONFIG_RADIO_SI470X) += si470x/
 obj-$(CONFIG_USB_MR800) += radio-mr800.o
 obj-$(CONFIG_RADIO_TEA5764) += radio-tea5764.o
-
+obj-$(CONFIG_RADIO_TAVARUA) += radio-tavarua.o
 EXTRA_CFLAGS += -Isound
